#!/bin/sh
###############Deploy##############

# If a command fails then the deploy stops set -e 
printf "\033[0;32mDeploying updates to GitHub...\033[0m\n"

mdbook build
cd book

git init
git branch -m site-code
git remote add origin git@github.com:januborer/januborer.github.io.git

current_branch=$(git branch --show-current)
git add -f .

msg="rebuilding site $(date)"
if [ -n "$*" ]; then
    msg="$*"
fi
git commit -m "$msg"

git push -f origin $current_branch
